### ISSUE TITLE
Stopping a docker container make crash all the zabbix container 's monitoring

### ISSUE THREAD

**Issue by cyril36** [dockermeetupsinbordeaux/docker-zabbix-sender#10]
To Reproduce : 
Image used : https://hub.docker.com/r/dockermeetupsinbordeaux/docker-zabbix-sender/~/dockerfile/

1. start docker-zabbix-sender
2. start another container
3. stop the another container and waits for its termination.
4. the service  docker-zabbix-sender called zabbix_sender crash and broke the pipe

Apparently it crashes at the line "self._endpoint_func(self._client, payload)" of the Collector.py when it create a subprocess (pipe broken) 

La stack :
2015-12-02 10:07:57,674 INFO     stats-emitter waiting for all collectors threads to terminate.
2015-12-02 10:07:58,017 INFO     stats-emitter collectors terminated successfully. See you bye!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/docker_zabbix_sender/collector.py", line 243, in run
    self._endpoint_func(self._client, payload)
  File "/usr/local/lib/python2.7/site-packages/docker_zabbix_sender/endpoint.py", line 60, in __call__
    self.emit(events)
  File "/usr/local/lib/python2.7/site-packages/docker_zabbix_sender/zabbix_sender.py", line 119, in emit
    self.zabbix_sender_p.stdin.write(fmt.format(**event))
IOError: [Errno 32] Broken pipe

Exception in thread za:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/docker_zabbix_sender/collector.py", line 73, in run
    for stats in stream:
  File "/usr/local/lib/python2.7/site-packages/docker/client.py", line 194, in _stream_helper
    data = reader.read(1)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 258, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.

Processes when the service crash and the pipe is broken:
top - 10:07:56 up 20 days, 17:49,  0 users,  load average: 0.01, 0.36, 3.32
Threads:   9 total,   1 running,   7 sleeping,   0 stopped,   1 zombie
%Cpu(s):  1.5 us,  0.1 sy,  0.0 ni, 98.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  16146748 total,  8604252 used,  7542496 free,    15136 buffers
KiB Swap:        0 total,        0 used,        0 free.  4461932 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
   12 root      20   0  470856  17192   3952 S  0.3  0.1   0:00.65 docker-zabbix-s
   13 root      20   0  470856  17192   3952 S  0.3  0.1   0:00.56 docker-zabbix-s
    1 root      20   0  470856  17192   3952 S  0.0  0.1   0:00.16 docker-zabbix-s
   11 root      20   0  470856  17192   3952 S  0.0  0.1   0:00.25 docker-zabbix-s
   14 root      20   0  470856  17192   3952 S  0.0  0.1   0:00.74 docker-zabbix-s
   21 root      20   0  470856  17192   3952 S  0.0  0.1   0:00.08 docker-zabbix-s
   10 root      20   0       0      0      0 Z  0.0  0.0   0:00.00 zabbix_sender
   15 root      20   0   21924   2012   1544 S  0.0  0.0   0:00.01 bash
   19 root      20   0   23620   1520   1108 R  0.0  0.0   0:00.07 top
top - 10:07:59 up 20 days, 17:50,  0 users,  load average: 0.01, 0.36, 3.32
Threads:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.1 sy,  0.0 ni, 99.5 id,  0.2 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  16146748 total,  8603384 used,  7543364 free,    15136 buffers
KiB Swap:        0 total,        0 used,        0 free.  4462560 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
    1 root      20   0  470856  17528   3952 S  0.0  0.1   0:00.16 docker-zabbix-s
   21 root      20   0  470856  17528   3952 S  0.0  0.1   0:00.08 docker-zabbix-s
   15 root      20   0   21924   2012   1544 S  0.0  0.0   0:00.01 bash
   19 root      20   0   23620   1520   1108 R  0.0  0.0   0:00.07 top
top - 10:08:02 up 20 days, 17:50,  0 users,  load average: 0.01, 0.35, 3.30
Threads:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.1 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  16146748 total,  8605112 used,  7541636 free,    15136 buffers
KiB Swap:        0 total,        0 used,        0 free.  4462584 cached Mem

**Comment by cyril36** [comment]
The issue is the self._docker._get(url, stream=True) that crash if the container does not exist.
I add a try/catch and call the function shutdown if a exception is raise.
It works like that but I am not a developper so there is maybe a better way to do it.

The fix in the below code in the collector.py file

def run(self):
        """Collect container metrics repeatedly. Does not returns
        unless the Docker stats stream is closed or the `shutdown` method
        is called.
        """
        previous_user_cpu = 0.0
        previous_kernel_cpu = 0.0
        previous_total_cpu = 0.0
        previous_system = 0.0
        previous_network_rx = 0.0
        previous_network_tx = 0.0
        start = True
        url = self._docker._url("/containers/{0}/stats".format(self.container))
        **try:
                self._response = self._docker._get(url, stream=True)
                stream = self._docker._stream_helper(self._response, decode=True)
                self._logger.info("DOCKER RESPONSE %s", self._response)
        finally:
            self._logger.info("FINALLY")
            self.shutdown()**
        try:
            for stats in stream:
                stats['timestamp']= int(time.time())
                # Provides additional fields that can be used by metrics plugins
                stats['name'] = self.name
                stats['id'] = self.container
