### ISSUE TITLE
docker-zabbix-sender not sending stats at all.

### ISSUE THREAD

**Issue by interInt** [dockermeetupsinbordeaux/docker-zabbix-sender#9]
Hi, 

I have been able to build and install the docker-zabbix-sender. but I an failing at the last point where I need to send stats to my remote zabbix server. 

I am running docker-zabbix-sender on a bare metal.  See stack trace below

 docker-zabbix-sender -v -c /etc/zabbix/zabbix_agentd.conf -z 10.18.0.20 -s zab_server02
2015-11-16 19:32:52,778 INFO     end-point Registered metrics entrypoint 'container-count'
2015-11-16 19:32:52,779 INFO     end-point Registered metrics entrypoint 'container-ip'
2015-11-16 19:32:52,779 INFO     end-point Registered metrics entrypoint 'cpu-count'
1
Traceback (most recent call last):
  File "/usr/bin/docker-zabbix-sender", line 9, in <module>
    load_entry_point('docker-zabbix-sender==0.3.3', 'console_scripts', 'docker-zabbix-sender')()
  File "/usr/lib/python2.7/site-packages/docker_zabbix_sender-0.3.3-py2.7.egg/docker_zabbix_sender/zabbix_sender.py", line 201, in run
    verbose=args.verbose if args.verbose is not None else 0
  File "/usr/lib/python2.7/site-packages/docker_zabbix_sender-0.3.3-py2.7.egg/docker_zabbix_sender/zabbix_sender.py", line 109, in __init__
    **kwargs
  File "/usr/lib/python2.7/site-packages/docker_zabbix_sender-0.3.3-py2.7.egg/docker_zabbix_sender/zabbix_sender.py", line 23, in __init__
    subprocess.Popen.__init__(self, ZabbixSenderProcess.cmdline(**kwargs), stdin=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

zab_server02 being the hostname where the agent and docker images are running off. 

I am not sure how to resolve this error. Any assistance will be highly appreciated.

**Comment by tristan0x** [comment]
Hi @interInt 

The error message suggests that `zabbix_sender` executable, part of Zabbix, cannot be found by `docker-zabbix-sender`.

Maybe it `zabbix_sender` is not installed installed, or unavailable in the `PATH` environment variable given to `docker-zabbix-sender`. Can you please check this ?

**Comment by interInt** [comment]
Thank you for the feedback @tristan0x 

I can confirm zabbix_sender is installed.

How can I check the path environment for docker-zabbix-sender?

**Comment by tristan0x** [comment]
From the environment (shell in terminal or the script from which your are launching `docker-zabbix-sender`, can you give me the output of:

```shell
echo $PATH
type zabbix_sender
```

**Comment by interInt** [comment]
I was able to run the command 

echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

thereafter, I created a soft link to the path, and it was able to start 

ln -s /opt/zabbix/agent/bin/zabbix_sender /usr/local/bin/zabbix_sender 

docker-zabbix-sender -v -c /etc/zabbix/zabbix_agentd.conf -z 10.18.0.20 -s zab_server02
2015-11-17 23:35:41,475 INFO     end-point Registered metrics entrypoint 'container-count'
2015-11-17 23:35:41,475 INFO     end-point Registered metrics entrypoint 'container-ip'
2015-11-17 23:35:41,475 INFO     end-point Registered metrics entrypoint 'cpu-count'
2
2015-11-17 23:35:41,485 INFO     stats-emitter Monitoring activity of container: 3443a790cf3a890899aa656d4f50b9085b2c6a00499765ff29520411e723977b
